### ISSUE TITLE
Help > Submit Feedback - user have ability to send empy field feedback 

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#32]
"Environment:
Win 11
Eudora 1.0.19.0

Precondition:
Eudora should be opened
Eudora should be into "Pale Blue" theme

STR:
Click on "Help "
Click on "Submit Feedback"
Click "Sent"

Actual Result:
user have ability to send empy field feedback 

Expected Result:
Field should have ability to validate the field on empty data.

https://www.loom.com/share/5d38bf9300da4e1388478772700453f0?sid=563e27ab-0bb3-4fca-bb2f-c570e12fcede

**Comment by ispeedonthe405** [comment]
Fixed in build 22
