### ISSUE TITLE
"Contents" do not work

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#36]
"Environment:
Win 11
Eudora 1.0.19.0

Precondition:
Eudora should be opened

STR:
Click on "Help" dropdown
Click on  "Contents"

Actual Result:
Contents - do not reacting on any clicks

Expected Result:
After clicking on "Contents " button - selection "Contents " should be opened.

**Comment by ispeedonthe405** [comment]
Quite right. Up until now there's been documentation to speak of, so there's nothing for the menu item to summon or show.

However, now that we're going forward with a technical writer, the first batch of documentation will be part of build 1.0.22.
