### ISSUE TITLE
Eudora crashing while creating no mailboxes 

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#40]
"Environment:
Win 11
Eudora 1.0.21.0

Precondition:
Eudora should be opened

STR:
Click "New mailbox"
Enter "qwe" name
Click "OK"
Click on just created "mailbox"

Actual Result:
Eudora crashing 

Expected Result:
Eudora should not  crash

attach:
https://www.loom.com/share/bb5fc03b8b85422491c875ad9f07b503?sid=24221dd7-f015-4862-9330-78a5280322da

**Comment by ispeedonthe405** [comment]
Oops. Fixed for nexr build.
