### ISSUE TITLE
User can't delete just created mailbox

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#41]
"Environment:
Win 11
Eudora 1.0.21.0

Precondition:
Eudora should be opened

STR:
Click "New mailbox"
Enter "qwe" name
Click "OK"
Click on just created "mailbox"
Click "Delete"

Actual Result:
no reaction after clicking

Expected Result:
mailbox should be deleted

attach:
https://www.loom.com/share/8292bcb5729e4508afc5022efbfebe08?sid=3ec49b42-cc86-4aae-a160-82d0cba772a6

**Comment by ispeedonthe405** [comment]
Fixed for next build.
