### ISSUE TITLE
New mailboxes do not apear into drop down selection

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#43]
"Environment:
Win 11
Eudora 1.0.22.0

Precondition:
Eudora should be opened

STR:
Click "New mailbox"
Enter "qwe" name
Click "OK"
Click on "mailbox" dropdown
check menu 

Actual Result:
New mailboxes do not apear into drop down selection

Expected Result:
it should track here

**Comment by ispeedonthe405** [comment]
Right, the menu manager needs to know about user mailboxes. That will be fixed in 23.
